apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-18
  namespace: postgres
spec:
  serviceName: postgres-18
  replicas: 1

  selector:
    matchLabels:
      app: postgres-18

  template:
    metadata:
      labels:
        app: postgres-18
    spec:
      containers:
        - name: postgres
          image: postgres:18
          imagePullPolicy: IfNotPresent

          ports:
            - name: postgres
              containerPort: 5432

          envFrom:
            - secretRef:
                name: postgres-admin-secret

          env:
            - name: POSTGRES_DB
              value: postgres
            - name: PGDATA
              value: /var/lib/postgresql/18/docker

          volumeMounts:
            - name: postgres-18-data
              mountPath: /var/lib/postgresql

          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - watersystem_ml
                - -d
                - postgres
            initialDelaySeconds: 10
            periodSeconds: 10

          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - watersystem_ml
                - -d
                - postgres
            initialDelaySeconds: 30
            periodSeconds: 20

  volumeClaimTemplates:
    - metadata:
        name: postgres-18-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi